# version: "3.8"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    volumes:
      - ./backend:/app
    command:
      ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://57.180.44.232:3000/api
      - BACKEND_API_BASE_URL=http://fastapi:8000/api
      - BACKEND_AUTH_URL=http://fastapi:8000/
    depends_on:
      - backend

  # nginx:
  #   image: nginx:latest
  #   container_name: nginxf
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - default

  minio:
    image: quay.io/minio/minio:latest
    container_name: s3-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      
    command: server --console-address ":9090" /data
    volumes:
      - ./minio/data:/data
    ports:
      - 9000:9000
      - 9090:9090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1s
      timeout: 10s
      retries: 5

  
  # docker起動時にバケット作成
  mc:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set s3-minio http://minio:9000 admin admin123;) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing s3-minio/image --region=ap-northeast-1;
      /usr/bin/mc anonymous set public s3-minio/image;
      exit 0;
      "

volumes:
  mongodb_data:
